services:
  - type: web
    name: ecommerce-django
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate
    startCommand: >-
      gunicorn config.wsgi:application \
      --bind 0.0.0.0:$PORT \
      --workers 4 \
      --timeout 120 \
      --log-level=debug \
      --access-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.6"
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "4"
    plan: free
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /
    healthCheckTimeout: 90
