services:
  - type: web
    name: silene-dor-chez-mermose
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput
    startCommand: gunicorn -c gunicorn_config.py ecommerce.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: RENDER
        value: "true"
    plan: free
    region: frankfurt
    autoDeploy: true
