# Generated by Django 5.2.4 on 2025-07-31 18:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_picture_path, verbose_name='Photo de profil'),
        ),
    ]
