# Generated by Django 5.2.4 on 2025-08-01 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_imagecategorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 étoile - Très mauvais'), (2, '2 étoiles - Mauvais'), (3, '3 étoiles - Moyen'), (4, '4 étoiles - Bon'), (5, '5 étoiles - Excellent')], help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('title', models.CharField(help_text='Titre de votre avis', max_length=200, verbose_name='Titre')),
                ('comment', models.TextField(help_text='Votre avis détaillé sur le produit', max_length=2000, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_purchased', models.BooleanField(default=False, help_text="Si l'utilisateur a acheté ce produit", verbose_name='Acheté')),
                ('is_approved', models.BooleanField(default=True, help_text="Si l'avis est approuvé par un modérateur", verbose_name='Approuvé')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs qui ont aimé cet avis')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.produit', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_review', violation_error_message='Vous avez déjà laissé un avis pour ce produit.')],
            },
        ),
    ]
