# Generated by Django 5.2.4 on 2025-08-01 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=10, verbose_name='Langue source')),
                ('target_language', models.CharField(max_length=10, verbose_name='Langue cible')),
                ('original_text', models.TextField(verbose_name='Texte original')),
                ('translated_text', models.TextField(verbose_name='Texte traduit')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de traduction',
                'verbose_name_plural': 'Historiques de traduction',
                'ordering': ('-created_at',),
            },
        ),
    ]
