# Generated by Django 5.2.4 on 2025-07-31 17:22

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.categorie_image_path, verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.categorie', verbose_name='Catégorie associée')),
            ],
            options={
                'verbose_name': 'Image de catégorie',
                'verbose_name_plural': 'Images des catégories',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
